DELIMITER $$
DROP PROCEDURE DEPOSITINTERESTUPDATEPROC;
CREATE PROCEDURE DEPOSITINTERESTUPDATEPROC()
BEGIN
    DECLARE ACCNO BIGINT;
    DECLARE BRANCHIFSC CHAR(11);
	DECLARE BALANCE FLOAT;
    DECLARE INTERESTRATE FLOAT;
    DECLARE FLAG INT DEFAULT 0;
	DECLARE DEPOSITCURSOR CURSOR FOR 
		SELECT DEPOSITINTERESTUPDATE.ACCOUNTNO, DEPOSITINTERESTUPDATE.BRANCHIFSC, DEPOSITINTERESTUPDATE.BALANCE
        FROM DEPOSITINTERESTUPDATE;
	DECLARE CONTINUE HANDLER 
    FOR NOT FOUND SET FLAG = 1;
	BEGIN
		SELECT INTERESTINFO.INTERESTRATE INTO INTERESTRATE FROM INTERESTINFO WHERE LOANTYPE='FIX';
		OPEN DEPOSITCURSOR;
        SELECT INTERESTINFO.INTERESTRATE FROM INTERESTINFO WHERE LOANTYPE='FIX';
        LABEL1 :LOOP
			FETCH DEPOSITCURSOR INTO ACCNO, BRANCHIFSC, BALANCE;
            IF FLAG=1 THEN
				LEAVE LABEL1;
			END IF;
				INSERT INTO DEPOSITINTERESTINFO VALUES(ACCNO, BRANCHIFSC, CURDATE(), (BALANCE*(INTERESTRATE/12))/100);
		END LOOP;
        CLOSE DEPOSITCURSOR;
	END;
END$$
DELIMITER ;


