DELIMITER $$
DROP PROCEDURE LOANINTERESTUPDATEPROC;
CREATE PROCEDURE LOANINTERESTUPDATEPROC()
BEGIN
    DECLARE LOANACCNO BIGINT;
    DECLARE BRANCHIFSC CHAR(11);
	DECLARE OUTSTANDING FLOAT;
	DECLARE INTERESTRATE FLOAT;
	DECLARE LOANSTATUS CHAR(1);
    DECLARE INTEREST FLOAT;
    DECLARE FLAG INT DEFAULT 0;
	DECLARE LOANCURSOR CURSOR FOR 
		SELECT LOANINTERESTUPDATE.LOANACCOUNTNO, LOANINTERESTUPDATE.BRANCHIFSC, LOANINTERESTUPDATE.OUTSTANDING, LOANINTERESTUPDATE.INTERESTRATE, LOANINTERESTUPDATE.LOANSTATUS 
        FROM LOANINTERESTUPDATE;
	DECLARE CONTINUE HANDLER 
    FOR NOT FOUND SET FLAG = 1;
	BEGIN
		OPEN LOANCURSOR;
        LABEL1 :LOOP
			FETCH LOANCURSOR INTO LOANACCNO, BRANCHIFSC, OUTSTANDING, INTERESTRATE, LOANSTATUS;
            IF FLAG=1 THEN
				LEAVE LABEL1;
			END IF;
            IF LOANSTATUS='A' THEN
				INSERT INTO LOANINTERESTRECORD VALUES(LOANACCNO, BRANCHIFSC, CURDATE(), (OUTSTANDING*(INTERESTRATE/12))/100);
            END IF;
		END LOOP;
        CLOSE LOANCURSOR;
	END;
END$$
DELIMITER ;


