CREATE TABLE CUSTOMERS
(
	CUSTOMERID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMERNAME VARCHAR(30) NOT NULL,
    SEX CHAR(1) NOT NULL,
    DATEOFBIRTH DATE NOT NULL,
    ADDRESSLINE1 VARCHAR(50) NOT NULL,
    ADDRESSLINE2 VARCHAR(50),
    CITY VARCHAR(20) NOT NULL,
    POSTALCODE BIGINT NOT NULL
);

ALTER TABLE CUSTOMERS
ADD CONSTRAINT CHECK_SEX CHECK (SEX IN ('M','F','O'));


INSERT INTO CUSTOMERS VALUES
(
	10000, 'SURESHKUMAR K', 'M', '1971-10-05', 'NEHRU STREET', 'ADYAR', 'CHENNAI', 600001
);

INSERT INTO CUSTOMERS VALUES
(
	NULL, 'ANITA R', 'F', '1971-11-19', 'NEHRU STREET', 'ADYAR', 'CHENNAI', 600001
);

SELECT * FROM CUSTOMERS;