CREATE TABLE LOANINTERESTRECORD
(
	LOANACCOUNTNO BIGINT NOT NULL,
    BRANCHIFSC CHAR(11) NOT NULL,
    TRANDATE DATE NOT NULL,
    INTEREST FLOAT
);

ALTER TABLE LOANINTERESTRECORD
ADD PRIMARY KEY (LOANACCOUNTNO, BRANCHIFSC, TRANDATE);

ALTER TABLE LOANINTERESTRECORD
ADD FOREIGN KEY (LOANACCOUNTNO, BRANCHIFSC)
REFERENCES LOANS (LOANACCOUNTNO, BRANCHIFSC);

INSERT INTO LOANINTERESTRECORD VALUES(10000, 'BANK0001000', CURDATE(), 50);
DELETE FROM LOANINTERESTRECORD WHERE TRANDATE=CURDATE() AND LOANACCOUNTNO=10000 AND BRANCHIFSC='BANK0001000';