CREATE TABLE DEPOSITINTERESTINFO
(
	ACCOUNTNO BIGINT NOT NULL,
    BRANCHIFSC CHAR(11) NOT NULL,
    TRANDATE DATE NOT NULL,
    INTEREST FLOAT,
    PRIMARY KEY (ACCOUNTNO, BRANCHIFSC, TRANDATE)
);

ALTER TABLE DEPOSITINTERESTINFO
ADD FOREIGN KEY (ACCOUNTNO, BRANCHIFSC)
REFERENCES ACCOUNTS (ACCOUNTNO, BRANCHIFSC);


  