CREATE TABLE LOANINTERESTRECORD
(
	LOANACCOUNTNO BIGINT NOT NULL,
    BRANCHIFSC CHAR(11) NOT NULL,
    TRANDATE DATE NOT NULL,
    INTEREST FLOAT,
    PRIMARY KEY (LOANACCOUNTNO, BRANCHIFSC, TRANDATE)
);


ALTER TABLE LOANINTERESTRECORD
ADD FOREIGN KEY (LOANACCOUNTNO, BRANCHIFSC)
REFERENCES LOANS (LOANACCOUNTNO, BRANCHIFSC);
