CREATE SCHEMA THE_BANK;
USE THE_BANK;

CREATE TABLE BRANCHES
(
	IFSCCODE CHAR(11) PRIMARY KEY,
    AREA VARCHAR(20) NOT NULL,
    CITY VARCHAR(20) NOT NULL,
    MANAGERID BIGINT NOT NULL UNIQUE
);

INSERT INTO BRANCHES VALUES('BANK0001000', 'ANNA UNIVERSITY', 'CHENNAI', 1);
UPDATE BRANCHES 
SET MANAGERID=10000
WHERE IFSCCODE='BANK0001000';

INSERT INTO BRANCHES VALUES('BANK0001001', 'ADYAR', 'CHENNAI', 2);

UPDATE BRANCHES 
SET MANAGERID=10001
WHERE IFSCCODE='BANK0001001';

ALTER TABLE BRANCHES
ADD FOREIGN KEY (MANAGERID)
REFERENCES EMPLOYEES (EMPLOYEEID);
DELETE FROM BRANCHES WHERE IFSCCODE='BANK0001002';
SELECT * FROM BRANCHES;
