CREATE TABLE TRANSACTIONS 
(
	TRANSACTIONID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TRANSACTIONDATE DATE NOT NULL,
    AMOUNT FLOAT NOT NULL,
    DEBITACCOUNTNO BIGINT,
    DEBITIFSC CHAR(11),
    CREDITACCOUNTNO BIGINT,
    CREDITIFSC CHAR(11)
);

ALTER TABLE TRANSACTIONS 
ADD FOREIGN KEY (DEBITACCOUNTNO, DEBITIFSC)
REFERENCES ACCOUNTS (ACCOUNTNO, BRANCHIFSC);

ALTER TABLE TRANSACTIONS 
ADD FOREIGN KEY (CREDITACCOUNTNO, CREDITIFSC)
REFERENCES ACCOUNTS (ACCOUNTNO, BRANCHIFSC);

INSERT INTO TRANSACTIONS VALUES(NULL, CURDATE(), 200, 10000, 'BANK0001001', 10000, 'BANK0001001');
INSERT INTO TRANSACTIONS VALUES(NULL, CURDATE(), 10000, NULL, '', 10003, 'BANK0001001');
INSERT INTO TRANSACTIONS VALUES(NULL, CURDATE(), 500, 10001, 'BANK0001000', NULL, '');

SELECT * FROM TRANSACTIONS;