CREATE TABLE DEPOSITINTERESTINFO
(
	ACCOUNTNO BIGINT NOT NULL,
    BRANCHIFSC CHAR(11) NOT NULL,
    TRANDATE DATE NOT NULL,
    INTEREST FLOAT,
    PRIMARY KEY (ACCOUNTNO, BRANCHIFSC, TRANDATE)
);

ALTER TABLE DEPOSITINTERESTINFO
ADD FOREIGN KEY (ACCOUNTNO, BRANCHIFSC)
REFERENCES ACCOUNTS (ACCOUNTNO, BRANCHIFSC);
INSERT INTO DEPOSITINTERESTINFO VALUES(10003, 'BANK0001001', CURDATE(), 500);
DELETE FROM DEPOSITINTERESTINFO WHERE ACCOUNTNO=10003 AND BRANCHIFSC='BANK0001001' AND TRANDATE=CURDATE();
  