CREATE TABLE EMPLOYEES
(
	EMPLOYEEID BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMPLOYEENAME VARCHAR(30) NOT NULL,
    SEX CHAR(1) NOT NULL,
    DATEOFBIRTH DATE NOT NULL,
    BRANCHIFSC CHAR(11) NOT NULL,
    DESIGNATION VARCHAR(20) NOT NULL,
    SALARY BIGINT NOT NULL,
    LOGPASSWORD VARCHAR(100) NOT NULL,
    ADDRESSLINE1 VARCHAR(50) NOT NULL,
    ADDRESSLINE2 VARCHAR(50),
    CITY VARCHAR(20) NOT NULL,
    POSTALCODE BIGINT NOT NULL
);

ALTER TABLE EMPLOYEES
ADD FOREIGN KEY (BRANCHIFSC)
REFERENCES BRANCHES (IFSCCODE);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT CHEECK_SEX CHECK (SEX IN ('M','F','O'));

INSERT INTO EMPLOYEES VALUES
(
	10000, 'SURESHKUMAR K', 'M', '1971-10-05', 'BANK0001000', 'MANAGER', 230000, 'ADMIN',
    'NEHRU STREET', 'ADYAR','CHENNAI','600001'
);

INSERT INTO EMPLOYEES VALUES
(
	NULL, 'SHAHID S', 'M', '2000-08-14', 'BANK0001000', 'CASHIER', 10000, 'ADMIN',
    'GREEN COLONY', 'TNAGAR','CHENNAI','600001'
);

SELECT * FROM EMPLOYEES;