CREATE SCHEMA THE_BANK;
USE THE_BANK;

CREATE TABLE BRANCHES
(
	IFSCCODE CHAR(11) PRIMARY KEY,
    AREA VARCHAR(20) NOT NULL,
    CITY VARCHAR(20) NOT NULL,
    MANAGERID BIGINT NOT NULL UNIQUE
);

INSERT INTO BRANCHES VALUES('BANK0001000', 'ANNA UNIVERSITY', 'CHENNAI', 1);

ALTER TABLE BRANCHES
ADD FOREIGN KEY (MANAGERID)
REFERENCES EMPLOYEES (EMPLOYEEID);

