CREATE TABLE LOANS
(
	LOANACCOUNTNO BIGINT NOT NULL AUTO_INCREMENT,
    BRANCHIFSC CHAR(11) NOT NULL,
    CUSTOMERID BIGINT NOT NULL,
    PRINCIPLE FLOAT NOT NULL,
    INTERESTAMT FLOAT,
    OUTSTANDING FLOAT NOT NULL,
    LOANSTATUS CHAR(1) NOT NULL,
    LOANSECURITY VARCHAR(20) NOT NULL,
    LOANTYPE CHAR(3) NOT NULL,
    APPROVEDBY BIGINT NOT NULL,
    PRIMARY KEY (LOANACCOUNTNO, BRANCHIFSC)
);
ALTER TABLE LOANS
ADD COLUMN (SACTIONDATE DATE);
DESC LOANS;
ALTER TABLE LOANS
ADD FOREIGN KEY (CUSTOMERID)
REFERENCES CUSTOMERS (CUSTOMERID);

ALTER TABLE LOANS 
ADD FOREIGN KEY (APPROVEDBY)
REFERENCES EMPLOYEES (EMPLOYEEID);

ALTER TABLE LOANS
ADD FOREIGN KEY (BRANCHIFSC)
REFERENCES BRANCHES (IFSCCODE);

ALTER TABLE LOANS
ADD FOREIGN KEY (LOANTYPE)
REFERENCES INTERESTINFO (LOANTYPE);

ALTER TABLE LOANS
ADD CONSTRAINT CHECK_LOANSTATUS CHECK (LOANSTATUS IN('A','I'));
INSERT INTO LOANS VALUES
(
10000, 'BANK0001000', 10000, 1000, 0, 1000,'A','LAND','HOM',10000,CURDATE()
); 
SELECT * FROM LOANS;
UPDATE LOANS SET INTERESTAMT=0 WHERE LOANACCOUNTNO=10000 AND BRANCHIFSC='BANK0001000';