CREATE TABLE INTERESTINFO 
(	
	LOANTYPE CHAR(3) NOT NULL,
    INTERESTRATE FLOAT NOT NULL,
	PRIMARY KEY (LOANTYPE)
);

INSERT INTO INTERESTINFO VALUES('EDU', 8.75);
INSERT INTO INTERESTINFO VALUES('HOM', 9.75);
INSERT INTO INTERESTINFO VALUES('AGR', 8.5);
