CREATE TABLE LOANPAYMENTS
(
	LOANPAYID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TRANDATE DATE NOT NULL,
    AMOUNT FLOAT,
    LOANACCOUNTNO BIGINT NOT NULL,
    LOANIFSC CHAR(11),
    BRANCHIFSC CHAR(11)
);

ALTER TABLE LOANPAYMENTS
ADD FOREIGN KEY (LOANACCOUNTNO, LOANIFSC)
REFERENCES LOANS (LOANACCOUNTNO, BRANCHIFSC);

INSERT INTO LOANPAYMENTS VALUES(10000, CURDATE(), 500, 10000, 'BANK0001000', 'BANK0001000');  

SELECT * FROM LOANPAYMENTS;

