CREATE TABLE ACCOUNTS
(
	ACCOUNTNO BIGINT AUTO_INCREMENT,
    BRANCHIFSC CHAR(11) ,
    CUSTOMERID BIGINT NOT NULL,
    ACCOUNTTYPE CHAR(1) NOT NULL,
    ACCSTATUS CHAR(1) NOT NULL,
    BALANCE FLOAT NOT NULL,
    
    PRIMARY KEY (ACCOUNTNO, BRANCHIFSC)
);

ALTER TABLE ACCOUNTS 
ADD FOREIGN KEY (BRANCHIFSC)
REFERENCES BRANCHES (IFSCCODE);

ALTER TABLE ACCOUNTS
ADD FOREIGN KEY (CUSTOMERID)
REFERENCES CUSTOMERS (CUSTOMERID);

ALTER TABLE ACCOUNTS
ADD CONSTRAINT CHECK_ACCOUNTTYPE CHECK (ACCOUNTTYPE IN ('S','C','F','R'));

ALTER TABLE ACCOUNTS
ADD CONSTRAINT CHECK_ACCSTATUS CHECK (ACCSTATUS IN ('A','I'));

INSERT INTO ACCOUNTS VALUES
(
	10000, 'BANK0001000', 10000, 'S', 'A', 0
);

INSERT INTO ACCOUNTS VALUES
(
	10000, 'BANK0001001', 10001, 'S', 'A', 0
);

INSERT INTO ACCOUNTS VALUES
(
	NULL, 'BANK0001000', 10000, 'S', 'A', 0
);

INSERT INTO ACCOUNTS VALUES
(
	NULL, 'BANK0001001', 10001, 'S', 'A', 0
);
INSERT INTO ACCOUNTS VALUES
(
	NULL, 'BANK0001001', 10001, 'F', 'A', 0
);
SELECT * FROM ACCOUNTS;
COMMIT;