USE THE_BANK;
DELIMITER $$
DROP TRIGGER MANAGER_UPDATE_AFTER;
CREATE TRIGGER MANAGER_UPDATE_AFTER
AFTER INSERT ON BRANCHES
FOR EACH ROW
BEGIN
        UPDATE EMPLOYEES
		SET EMPLOYEES.BRANCHIFSC = NEW.IFSCCODE, EMPLOYEES.DESIGNATION = 'MANAGER'
		WHERE EMPLOYEES.EMPLOYEEID = NEW.MANAGERID;
END$$
DELIMITER ;