DELIMITER $$
CREATE TRIGGER DEPOSITINTEREST_UPDATE_AFTER
AFTER INSERT ON DEPOSITINTERESTINFO
FOR EACH ROW
BEGIN
        UPDATE ACCOUNTS
		SET ACCOUNTS.BALANCE = ACCOUNTS.BALANCE + NEW.INTEREST
		WHERE ACCOUNTS.ACCOUNTNO = NEW.ACCOUNTNO
		AND ACCOUNTS.BRANCHIFSC = NEW.BRANCHIFSC
		AND ACCOUNTS.ACCSTATUS = 'A';
END$$
DELIMITER ;