USE THE_BANK;
DELIMITER $$
DROP TRIGGER TRANSACTION_BALANCE_UPDATE_AFTER;
CREATE TRIGGER TRANSACTION_BALANCE_UPDATE_AFTER
AFTER INSERT ON TRANSACTIONS
FOR EACH ROW
BEGIN
			DECLARE EXISTING_BALANCE BIGINT;
            SELECT ACCOUNTS.BALANCE INTO EXISTING_BALANCE
            FROM ACCOUNTS
            WHERE ACCOUNTS.ACCOUNTNO = NEW.DEBITACCOUNTNO
			AND ACCOUNTS.BRANCHIFSC = NEW.DEBITIFSC
            AND ACCOUNTS.ACCSTATUS = 'A';
            
			IF (EXISTING_BALANCE >= NEW.AMOUNT AND NEW.DEBITACCOUNTNO IS NOT NULL AND NEW.CREDITACCOUNTNO IS NOT NULL) THEN	
				BEGIN
					UPDATE ACCOUNTS
					SET ACCOUNTS.BALANCE = BALANCE - NEW.AMOUNT
					WHERE ACCOUNTS.ACCOUNTNO = NEW.DEBITACCOUNTNO
					AND ACCOUNTS.BRANCHIFSC = NEW.DEBITIFSC
                    AND ACCOUNTS.ACCSTATUS = 'A';
    
					UPDATE ACCOUNTS
					SET ACCOUNTS.BALANCE = BALANCE + NEW.AMOUNT
					WHERE ACCOUNTS.ACCOUNTNO = NEW.CREDITACCOUNTNO
					AND ACCOUNTS.BRANCHIFSC = NEW.CREDITIFSC
                    AND ACCOUNTS.ACCSTATUS = 'A';
				END;
			ELSEIF (NEW.DEBITACCOUNTNO IS NULL) THEN	
				BEGIN
					UPDATE ACCOUNTS
					SET ACCOUNTS.BALANCE = BALANCE + NEW.AMOUNT
					WHERE ACCOUNTS.ACCOUNTNO = NEW.CREDITACCOUNTNO
					AND ACCOUNTS.BRANCHIFSC = NEW.CREDITIFSC
                    AND ACCOUNTS.ACCSTATUS = 'A';
				END;
			ELSEIF (NEW.CREDITACCOUNTNO IS NULL) THEN	
				BEGIN
					UPDATE ACCOUNTS
					SET ACCOUNTS.BALANCE = BALANCE - NEW.AMOUNT
					WHERE ACCOUNTS.ACCOUNTNO = NEW.DEBITACCOUNTNO
					AND ACCOUNTS.BRANCHIFSC = NEW.DEBITIFSC
                    AND ACCOUNTS.ACCSTATUS = 'A';
				END;
			END IF;
END$$
DELIMITER ;

