DELIMITER $$
CREATE TRIGGER LOANINTEREST_UPDATE_AFTER
AFTER INSERT ON LOANINTERESTRECORD
FOR EACH ROW
BEGIN
        UPDATE LOANS
		SET LOANS.INTERESTAMT = LOANS.INTERESTAMT + NEW.INTEREST
		WHERE LOANS.LOANACCOUNTNO = NEW.LOANACCOUNTNO
		AND LOANS.BRANCHIFSC = NEW.BRANCHIFSC
		AND LOANS.LOANSTATUS = 'A';
        
        UPDATE LOANS
		SET LOANS.OUTSTANDING = LOANS.OUTSTANDING + NEW.INTEREST
		WHERE LOANS.LOANACCOUNTNO = NEW.LOANACCOUNTNO
		AND LOANS.BRANCHIFSC = NEW.BRANCHIFSC
		AND LOANS.LOANSTATUS = 'A';
END$$
DELIMITER ;

