CREATE VIEW LOANINTERESTUPDATE AS
SELECT LOANS.LOANACCOUNTNO, LOANS.BRANCHIFSC, LOANS.LOANSTATUS, LOANS.OUTSTANDING, LOANS.LOANTYPE, INTERESTINFO.INTERESTRATE
FROM LOANS, INTERESTINFO
WHERE LOANS.LOANTYPE = INTERESTINFO.LOANTYPE;