CREATE VIEW CUSTOMERLOAN
AS
SELECT CUSTOMERS.CUSTOMERID,CUSTOMERS.CUSTOMERNAME, LOANS.LOANACCOUNTNO, LOANS.BRANCHIFSC, BRANCHES.AREA, 
LOANS.LOANTYPE,LOANS.LOANSTATUS, LOANS.PRINCIPLE,LOANS.INTERESTAMT, LOANS.OUTSTANDING
FROM CUSTOMERS, LOANS, BRANCHES
WHERE CUSTOMERS.CUSTOMERID = LOANS.CUSTOMERID
AND BRANCHES.IFSCCODE = LOANS.BRANCHIFSC;