CREATE VIEW DEPOSITINTERESTUPDATE AS
SELECT ACCOUNTS.ACCOUNTNO, ACCOUNTS.BRANCHIFSC, ACCOUNTS.BALANCE
FROM ACCOUNTS
WHERE (ACCOUNTS.ACCOUNTTYPE='F' OR ACCOUNTS.ACCOUNTTYPE='R')
AND ACCOUNTS.ACCSTATUS='A';
