CREATE VIEW CUSTOMERACCOUNT
AS
SELECT CUSTOMERS.CUSTOMERID,CUSTOMERS.CUSTOMERNAME, ACCOUNTS.ACCOUNTNO, ACCOUNTS.BRANCHIFSC, BRANCHES.AREA, 
ACCOUNTS.ACCOUNTTYPE, ACCOUNTS.ACCSTATUS, ACCOUNTS.BALANCE
FROM CUSTOMERS, ACCOUNTS, BRANCHES
WHERE CUSTOMERS.CUSTOMERID = ACCOUNTS.CUSTOMERID
AND BRANCHES.IFSCCODE = ACCOUNTS.BRANCHIFSC;

